
package com.acme.training.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ShoppingCartWSService", targetNamespace = "http://ws.training.acme.com/", wsdlLocation = "http://10.0.15.57:8080/shoppingcart?wsdl")
public class ShoppingCartWSService
    extends Service
{

    private final static URL SHOPPINGCARTWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.acme.training.ws.ShoppingCartWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.acme.training.ws.ShoppingCartWSService.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.15.57:8080/shoppingcart?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.15.57:8080/shoppingcart?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SHOPPINGCARTWSSERVICE_WSDL_LOCATION = url;
    }

    public ShoppingCartWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShoppingCartWSService() {
        super(SHOPPINGCARTWSSERVICE_WSDL_LOCATION, new QName("http://ws.training.acme.com/", "ShoppingCartWSService"));
    }

    /**
     * 
     * @return
     *     returns ShoppingCartWS
     */
    @WebEndpoint(name = "ShoppingCartWSPort")
    public ShoppingCartWS getShoppingCartWSPort() {
        return super.getPort(new QName("http://ws.training.acme.com/", "ShoppingCartWSPort"), ShoppingCartWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShoppingCartWS
     */
    @WebEndpoint(name = "ShoppingCartWSPort")
    public ShoppingCartWS getShoppingCartWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.training.acme.com/", "ShoppingCartWSPort"), ShoppingCartWS.class, features);
    }

}
